name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 23 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23.0.2'
          cache: 'sbt'
      - name: Install sbt 1.9.8
        run: |
          curl -L -o sbt.deb https://repo.scala-sbt.org/scalasbt/debian/sbt-1.9.8.deb
          sudo dpkg -i sbt.deb
          sbt sbtVersion
      - name: Run tests
        run: sbt -v test
